extends:
  - stylelint-config-standard-scss
  - stylelint-config-prettier-scss
  - stylelint-config-html/html
  - stylelint-config-html/svelte
plugins: stylelint-use-nesting
rules:
  custom-property-empty-line-before: never
  selector-pseudo-class-no-unknown:
    - true
    - ignorePseudoClasses:
        - global
  csstools/use-nesting: always
